services:
  - type: web
    name: todo-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://hayel:<db_password>@cluster0.yfblnu0.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: سر_سري_قوي_هنا
      - key: PORT
        value: 10000